# Generated by Django 5.1.1 on 2024-11-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_especialidad', models.CharField(max_length=6)),
                ('id_consultorio', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=40)),
                ('horario', models.CharField(max_length=12)),
            ],
        ),
    ]
