# Generated by Django 5.1.1 on 2024-11-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_paciente', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=150)),
                ('servicio', models.CharField(max_length=30)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
    ]
