# Generated by Django 5.1.1 on 2024-11-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_empleado', models.CharField(max_length=6)),
                ('id_paciente', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_at', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
